---
  - name: Playbook for installation, software, application
    hosts: localhost

    vars_files:
      - ../group_vars/all

    tasks:
      
      - name: Installing zookeeper ... ....  ....
        apt:
          name: zookeeper
          state: present
        become: yes

      - name: Creating zookeeper service  ... ... ... ...
        template:
          src: zookeeper.service.j2
          dest: "/etc/init.d/zookeeper"
        notify: reloading rc.d
        become: yes



      - name: Creating log directories ... ... ... ...
        file:
          path: "{{ zookeeper_log_dir }}"
          mode: 0755
          owner: "{{ zookeeper_user }}"
          group: "{{ zookeeper_group }}"
          state: directory
        notify: Restart zookeeper
        become: yes

      - name: Creating db directory ... ... ... ...
        file:
          path: "{{ zookeeper_db_dir }}"
          mode: 0755
          owner: "{{ zookeeper_user }}"
          group: "{{ zookeeper_group }}"
          state: directory
        notify: Restart zookeeper
        become: yes

      - name: Creating config directory ...  ...  ...
        file:
          path: "{{ zookeeper_conf_dir }}"
          mode: 0755
          owner: "{{ zookeeper_user }}"
          group: "{{ zookeeper_group }}"
          state: directory
        notify: Restart zookeeper
        become: yes

      - name: Create zookeeper config files ... ... ...
        template:
          src: zoo.cfg.j2
          dest: "{{ zookeeper_conf }}"
        notify: Restart zookeeper
        become: yes

      - name: Creating myid ... ... ... ...
        template:
          src: myid.j2
          dest: "{{ zookeeper_db_dir }}/myid"
        when:
          - zookeeper_myid is defined
        notify: Restart zookeeper
        become: yes

      - name: Starting and enabilng the zookeeper service ... ...  ...
        service:
          name: "{{ zookeeper_service }}"
          enabled: true
          state: started
        become: yes
